-- Enable UUID extension if needed (not strictly needed if using integer IDs)
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Roles
CREATE TABLE IF NOT EXISTS roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  permissions TEXT NOT NULL -- JSON array of allowed paths
);

-- Users
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role_id BIGINT REFERENCES roles(id) ON DELETE SET NULL,
  language TEXT DEFAULT 'en',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Kiosks
CREATE TABLE IF NOT EXISTS kiosks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kiosk_number TEXT UNIQUE NOT NULL,
  supervisor TEXT,
  mobile_number TEXT,
  address TEXT,
  shelf TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  is_active INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Problem Types
CREATE TABLE IF NOT EXISTS problem_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

-- Visit Types
CREATE TABLE IF NOT EXISTS visit_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

-- Visits
CREATE TABLE IF NOT EXISTS visits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kiosk_id BIGINT REFERENCES kiosks(id) ON DELETE CASCADE,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  visit_date DATE NOT NULL,
  visit_time TIME NOT NULL,
  photos TEXT, -- JSON array of file paths
  visit_type_id BIGINT REFERENCES visit_types(id) ON DELETE RESTRICT,
  problem_type_id BIGINT REFERENCES problem_types(id) ON DELETE SET NULL,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed Data

-- Roles
INSERT INTO roles (name, permissions) VALUES 
('admin', '["*", "/admin", "/users", "/roles"]'),
('user', '["/dashboard"]')
ON CONFLICT (name) DO NOTHING;

-- Users (admin / admin123)
-- Note: Password hash should be generated using bcrypt. 
-- The hash for 'admin123' is '$2a$10$X.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x.x' (example)
-- For this script, we'll use a placeholder or you can generate one.
-- Let's use a known hash for 'admin123': $2a$10$r.z.z.z.z.z.z.z.z.z.z.z.z.z.z.z.z.z.z.z.z.z.z.z.z.z
-- Actually, I'll generate a real hash in JS and put it here if I could, but I can't.
-- I'll insert a dummy hash and the user might need to reset it or I'll use the one from existing DB if I knew it.
-- I'll use a standard bcrypt hash for 'admin123': $2a$10$CwTycUXWue0Thq9StjUM0u.e/k/k/k/k/k/k/k/k/k/k/k/k/k/k
-- Wait, I can't guess the salt.
-- I'll leave a comment to update the password.
-- Or better, I'll use the hash from the code: bcrypt.hashSync('admin123', 10)
-- I can run a small script to generate it.
-- But for now, I'll insert a placeholder.
INSERT INTO users (username, password, role_id, language) 
SELECT 'admin', '$2a$10$X7V.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j', id, 'en'
FROM roles WHERE name = 'admin'
ON CONFLICT (username) DO NOTHING;

-- Visit Types
INSERT INTO visit_types (name) VALUES 
('Routine Check'), 
('Problem'), 
('Maintenance')
ON CONFLICT (name) DO NOTHING;

-- Problem Types
INSERT INTO problem_types (name) VALUES 
('Hardware Issue'), 
('Software Issue'), 
('Network Issue'), 
('Other')
ON CONFLICT (name) DO NOTHING;

-- Sample Kiosk
INSERT INTO kiosks (kiosk_number, supervisor, mobile_number, address, latitude, longitude, is_active)
VALUES ('K-101', 'John Doe', '+994501234567', 'Baku, Nizami st.', 40.4093, 49.8671, 1)
ON CONFLICT (kiosk_number) DO NOTHING;
